on: [push]

name: Node.js

jobs:

  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.RNAzureCreds }}

    - uses: azure/k8s-actions/docker-login@master
      with:
        login-server: ronacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ronacr.azurecr.io/nodejssampleapp:${{ github.sha }}
        docker push ronacr.azurecr.io/nodejssampleapp:${{ github.sha }} 
      
    - uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'rondocker'
        images: 'ronacr.azurecr.io/nodejssampleapp:${{ github.sha }}'
