# on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/k8s-actions/docker-login@master
      with:
        loginServer: ronacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        email: ronai@microsoft.com
    
    - run: |
        docker build . -t ronacr.azurecr.io/nodejssampleapp:${{ github.sha }}
        docker push ronacr.azurecr.io/nodejssampleapp:${{ github.sha }} 
      
    - uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'rondocker'
        images: 'ronacr.azurecr.io/nodejssampleapp:${{ github.sha }}'
        id: webapp-id
